"""
Django settings for dropshipping project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from decimal import Decimal, InvalidOperation
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Load KEY=VALUE pairs from a local .env file (never committed to git).

    Returns the set of keys that came from the file, so the rest of this module
    can tell a developer's `.env` apart from real environment variables.
    """
    keys = set()
    if not path.exists():
        return keys
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value
            keys.add(key)
    return keys


def env_bool(name, default=False):
    """Read a boolean environment variable (1/true/yes/on)."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=None):
    """Read a comma-separated environment variable into a list."""
    items = [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]
    return items or list(default or [])


def env_decimal(name, default):
    """Read a decimal environment variable, falling back to ``default``.

    A typo in the environment (or in `.env`) must never take the checkout down,
    so an unparsable value is ignored and the default is used instead.
    """
    raw = os.environ.get(name, '').strip()
    if not raw:
        return Decimal(default)
    try:
        return Decimal(raw)
    except (InvalidOperation, ValueError):
        return Decimal(default)


_ENV_FILE_KEYS = _load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# Render sets RENDER=true on every service it runs, which lets this single
# settings module behave like a development box locally and like production on
# Render without extra configuration.

ON_RENDER = env_bool('RENDER')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=not ON_RENDER)
if ON_RENDER and 'DEBUG' in _ENV_FILE_KEYS:
    # `.env` is a local-development convenience, so it must never be able to
    # switch off the production hardening at the bottom of this file. Export
    # DEBUG=True as a real environment variable if you truly need it on Render.
    DEBUG = False

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'The SECRET_KEY environment variable must be set when DEBUG is disabled.'
        )
    # Local development fallback only — never used when DEBUG is off.
    SECRET_KEY = 'django-insecure-l1o!b2x#^_9e=66g$nl6ysieyry_dv+&7d+7ri%p171m-^*ahf'

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['127.0.0.1', 'localhost', 'testserver', '.onrender.com'],
)
# Render injects the service's public hostname/URL at runtime.
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])

# Needed for POSTs (admin login, sign in, checkout) coming from the Render
# hostname once DEBUG is off. Render's proxy already redirects http -> https.
_csrf_origins = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
if os.environ.get('RENDER_EXTERNAL_URL'):
    _csrf_origins.append(os.environ['RENDER_EXTERNAL_URL'])
if not DEBUG and not _csrf_origins:
    _csrf_origins.append('https://*.onrender.com')
CSRF_TRUSTED_ORIGINS = sorted({origin.rstrip('/') for origin in _csrf_origins})

# Optional OAuth credentials. Set these in the deployment environment before
# enabling Google or Apple account linking.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
APPLE_CLIENT_ID = os.environ.get('APPLE_CLIENT_ID', '')
APPLE_CLIENT_SECRET = os.environ.get('APPLE_CLIENT_SECRET', '')


# Payments — three rails: Paystack (Naira), PayPal (USD) and Pi Network (π).
#
# Every credential below lives in the environment only (locally in the
# git-ignored `.env`, in production in Render's Environment tab). A rail turns
# itself on the moment its credentials exist: the checkout page then offers it,
# and hides it otherwise, so a missing key can never break the whole checkout.

# Paystack — card / bank transfer / USSD in Naira. The public key is served to
# the browser for the inline popup; the secret key stays server-side and is the
# only thing used to initialise and verify a transaction.
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', '').strip()
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '').strip()

# PayPal — the official JS SDK buttons plus server-side create/capture.
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '').strip()
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '').strip()
# "live" for real money, anything else (default) uses the sandbox.
PAYPAL_MODE = (os.environ.get('PAYPAL_MODE', 'sandbox').strip().lower() or 'sandbox')
PAYPAL_API_BASE = os.environ.get(
    'PAYPAL_API_BASE',
    'https://api-m.paypal.com' if PAYPAL_MODE == 'live' else 'https://api-m.sandbox.paypal.com',
).rstrip('/')

# Pi Network — the app's API key (from the Pi Developer Portal) authorises the
# server-side approve/complete calls made by the Pi Browser SDK flow.
PI_API_KEY = os.environ.get('PI_API_KEY', '').strip()
# Wallet that receives Pi payments (also shown to buyers who pay from a normal
# browser, where the Pi SDK is unavailable).
PI_WALLET_ADDRESS = os.environ.get('PI_WALLET_ADDRESS', '').strip()
PI_API_BASE = os.environ.get('PI_API_BASE', 'https://api.minepi.com').rstrip('/')
# Pi Developer Portal sandbox mode. Leave off for the production Pi app.
PI_SANDBOX = env_bool('PI_SANDBOX', default=False)
# Allow a manual Pi transfer (buyer sends Pi to PI_WALLET_ADDRESS and quotes the
# order reference) when the Pi Browser SDK cannot be used. The order is recorded
# as awaiting confirmation so a human can reconcile it.
PI_MANUAL_TRANSFER = env_bool('PI_MANUAL_TRANSFER', default=True)

# Shop prices are stored in USD. These rates decide how much the buyer is
# charged when they pick a local rail (Naira) or Pi.
NGN_PER_USD = env_decimal('NGN_PER_USD', '1600')
PI_PER_USD = env_decimal('PI_PER_USD', '2')

# Timeout (seconds) for outbound calls to the payment providers.
PAYMENT_HTTP_TIMEOUT = int(os.environ.get('PAYMENT_HTTP_TIMEOUT', '25'))

# Escrow (2%) + platform (1%) fees added to the cart subtotal at checkout. These
# mirror the fee breakdown shown on the checkout pages.
CHECKOUT_ESCROW_FEE_RATE = env_decimal('CHECKOUT_ESCROW_FEE_RATE', '0.02')
CHECKOUT_PLATFORM_FEE_RATE = env_decimal('CHECKOUT_PLATFORM_FEE_RATE', '0.01')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'accounts',
    'dashboards',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves the collected static files straight from the WSGI app,
    # which is how CSS/JS/images are delivered on Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dropshipping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dropshipping.context_processors.drophub_rates',
            ],
        },
    },
]

WSGI_APPLICATION = 'dropshipping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# DATABASE_URL drives the production database (Postgres on Render — e.g. Neon).
# Locally (no DATABASE_URL) the project falls back to the bundled SQLite file
# so `runserver` keeps working out of the box.
#
# IMPORTANT (Render persistence): Render's filesystem is EPHEMERAL — any file
# written after boot (including db.sqlite3) is wiped on every sleep/wake,
# restart and deploy. That is why "upload a product, see it, sleep, gone" was
# happening: without DATABASE_URL the app silently wrote to SQLite and lost it.
# In production (DEBUG off) we now FAIL FAST with a clear error instead of
# silently using SQLite, so a missing DATABASE_URL can never eat seller data.

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '0')),
            conn_health_checks=True,
        ),
    }
    # Neon's pooled (-pooler) endpoint is PgBouncer in transaction mode, where
    # server-side cursors and long-lived connections are not safe to rely on.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DATABASE_URL is not set. On Render, add a Postgres database '
            '(e.g. Neon) and set DATABASE_URL in the Environment tab — '
            'otherwise seller products/orders are stored in ephemeral SQLite '
            'and disappear after every sleep, restart or deploy.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'   # UTC+1 — Nigeria Standard Time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Where `collectstatic` writes the files WhiteNoise then serves in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

AUTH_USER_MODEL = 'accounts.User'

# ── Performance: in-memory cache (local) / Redis (production) ──────────────
# On Render, set REDIS_URL to a Redis instance URL to get a shared cache.
# Locally (and on free Render tiers without Redis) we use LocMemCache, which
# still helps by throttling expensive recurring operations per-process.
_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
            'TIMEOUT': 300,
            'OPTIONS': {'socket_connect_timeout': 2, 'socket_timeout': 2},
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'drophub-local',
        }
    }

# Use the cache for session storage — faster than a DB read on every request.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Keep DB connections alive between requests (speeds up SQLite + Postgres).
if not DATABASE_URL:
    # Local SQLite — reuse the same connection per thread
    DATABASES['default']['CONN_MAX_AGE'] = None  # persistent

# Uploaded files (e.g. seller verification documents).
# MEDIA_ROOT can be pointed at a Render persistent disk mount (for example
# /var/data/media) so uploads survive deploys; otherwise it lives on the
# service's ephemeral disk and is served by Django when SERVE_MEDIA is on.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT') or (BASE_DIR / 'media'))
SERVE_MEDIA = env_bool('SERVE_MEDIA', default=True)

LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/dashboards/'
LOGOUT_REDIRECT_URL = '/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# With no EMAIL_HOST configured, mail is written to the logs (same behaviour as
# the original console backend). Set EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD
# (and optionally EMAIL_PORT/EMAIL_USE_TLS) to send real mail.

_email_backend = os.environ.get('DJANGO_EMAIL_BACKEND', '').strip()
if not _email_backend:
    # SMTP as soon as credentials exist, otherwise log the email instead of
    # failing a deploy because no mailbox has been configured yet.
    _email_backend = (
        'django.core.mail.backends.smtp.EmailBackend'
        if os.environ.get('ZEPTOMAIL_SMTP_PASSWORD') or os.environ.get('EMAIL_HOST')
        else 'django.core.mail.backends.console.EmailBackend'
    )

MAILERS = {
    'default': {
        'BACKEND': _email_backend,
    },
}

if _email_backend.endswith('smtp.EmailBackend'):
    MAILERS['default']['OPTIONS'] = {
        'host': os.environ.get('ZEPTOMAIL_SMTP_HOST', os.environ.get('EMAIL_HOST', 'smtp.zeptomail.com')),
        'port': int(os.environ.get('ZEPTOMAIL_SMTP_PORT', os.environ.get('EMAIL_PORT', '587'))),
        'username': os.environ.get('ZEPTOMAIL_SMTP_USERNAME', os.environ.get('EMAIL_HOST_USER', 'emailapikey')),
        'password': os.environ.get('ZEPTOMAIL_SMTP_PASSWORD', os.environ.get('EMAIL_HOST_PASSWORD', '')),
        'use_tls': env_bool('ZEPTOMAIL_SMTP_USE_TLS', default=True),
    }

# Django's password-reset views use these standard settings.  For ZeptoMail,
# set ZEPTOMAIL_SMTP_PASSWORD to the SMTP password from its SMTP/API page and
# ZEPTOMAIL_FROM_EMAIL to an address in your verified sending domain.
DEFAULT_FROM_EMAIL = os.environ.get('ZEPTOMAIL_FROM_EMAIL', os.environ.get('DEFAULT_FROM_EMAIL', ''))


# Production hardening — applied whenever DEBUG is off (i.e. on Render).
if not DEBUG:
    # Render terminates TLS at its proxy and forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Off by default on purpose: enable (e.g. 31536000) once a custom domain is
    # fully live, since HSTS is remembered by browsers for the whole max-age.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS')
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD')


# Logging — everything goes to stdout so it shows up in Render's log stream.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

