# Generated by Django 6.1.1 on 2026-09-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=120)),
                ('store_name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=80)),
                ('country', models.CharField(default='Nigeria', max_length=80)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID (NIN slip / card)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], default='national_id', max_length=20)),
                ('id_number', models.CharField(default='', max_length=60)),
                ('document', models.FileField(blank=True, null=True, upload_to='seller_docs/')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Under review'), ('verified', 'Verified'), ('rejected', 'Needs attention')], default='unverified', max_length=12)),
                ('reviewer_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
