# Generated by Django 6.1.1 on 2026-09-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('store_name', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('price', models.CharField(blank=True, default='', max_length=30)),
                ('old_price', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('image_static', models.CharField(blank=True, default='', max_length=200)),
                ('badge', models.CharField(blank=True, default='', max_length=40)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product_slug')},
            },
        ),
    ]
