# Generated by Django 6.1.1 on 2026-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_order_delivery_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('NGN', 'NGN — Nigerian Naira'), ('PI', 'Pi Network')], default='USD', max_length=5),
        ),
    ]
