# Generated by Django 6.1.1 on 2026-09-18 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_boostorder_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('method', models.CharField(choices=[('pi', 'Pi Network'), ('paypal', 'PayPal'), ('paystack', 'Paystack')], max_length=10)),
                ('purpose', models.CharField(choices=[('checkout', 'Marketplace checkout'), ('boost', 'Product boost')], default='checkout', max_length=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('order_pks', models.JSONField(blank=True, default=list)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
