# Generated by Django 6.1.1 on 2026-09-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_order_payment_reference_paymentintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('USD_TO_NGN', 'USD → NGN  (Naira per dollar)'), ('USD_TO_PI', 'USD → PI   (Pi per dollar)')], max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['pair'],
            },
        ),
    ]
