# Generated by Django 6.1.1 on 2026-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pi_pending', 'Pi transfer pending review')], default='pending', max_length=10),
        ),
    ]
