# Generated by Django 6.1.1 on 2026-09-19 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_alter_paymentintent_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('refund_method', models.CharField(blank=True, default='', max_length=20)),
                ('refund_bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('refund_account_no', models.CharField(blank=True, default='', max_length=60)),
                ('refund_account_name', models.CharField(blank=True, default='', max_length=120)),
                ('refund_wallet', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved — Refund Approved'), ('rejected', 'Rejected')], default='open', max_length=12)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_complaints', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_complaint', to='dashboards.order')),
            ],
            options={
                'verbose_name': 'Refund Complaint',
                'verbose_name_plural': 'Refund Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('read_by_buyer', models.BooleanField(default=False)),
                ('read_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboards.refundcomplaint')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerPayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_record', to='dashboards.order')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_marked', to=settings.AUTH_USER_MODEL)),
                ('payout_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_records', to='dashboards.sellerpayoutmethod')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Payout Record',
                'verbose_name_plural': 'Seller Payout Records',
                'ordering': ['-paid_at'],
            },
        ),
    ]
