# Generated by Django 6.1.1 on 2026-09-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_refund_complaint_payout_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostorder',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
