# Generated by Django 6.1.1 on 2026-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('category', models.CharField(choices=[('playbook', 'Seller Playbooks'), ('pi-commerce', 'Pi Commerce'), ('escrow-trust', 'Escrow & Trust'), ('news', 'Marketplace News'), ('case-study', 'Case Studies')], default='news', max_length=20)),
                ('tag_label', models.CharField(blank=True, default='', help_text="Short tag shown on the card, e.g. 'PI COMMERCE'", max_length=60)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='', help_text='HTML or plain text. Displayed on the detail page.')),
                ('image_url', models.URLField(blank=True, default='', help_text='Unsplash/external cover image URL')),
                ('image', models.ImageField(blank=True, help_text='Uploaded cover image (overrides image_url)', null=True, upload_to='blog/')),
                ('author_name', models.CharField(default='DropHub Team', max_length=120)),
                ('author_role', models.CharField(blank=True, default='', help_text="e.g. 'Head of Seller Growth'", max_length=160)),
                ('author_avatar_url', models.URLField(blank=True, default='')),
                ('read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the spotlight featured article')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
